name: ouchi_stocker
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment: { sdk: ^3.4.3 }

dependencies:
  flutter: { sdk: flutter }
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test: { sdk: flutter }
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
