name: ouchi_stocker
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment: { sdk: ^3.4.3 }

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  flutter_test: { sdk: flutter }
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
