// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI09m3qOH5qHX_qawYqq3QrP46xzLWkDM',
    appId: '1:593758522061:web:8ad385dd335066f1883784',
    messagingSenderId: '593758522061',
    projectId: 'ouchi-stocker',
    authDomain: 'ouchi-stocker.firebaseapp.com',
    storageBucket: 'ouchi-stocker.appspot.com',
    measurementId: 'G-FB3YE5XG2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxGSZB5G4KNfg_yEc5oVhQVg5a1UA9m4',
    appId: '1:593758522061:android:007eba8ec92079a0883784',
    messagingSenderId: '593758522061',
    projectId: 'ouchi-stocker',
    storageBucket: 'ouchi-stocker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJLjvIH28B3BwH-FCvG65Fs77_-3hrE2I',
    appId: '1:593758522061:ios:3b64527665b02e53883784',
    messagingSenderId: '593758522061',
    projectId: 'ouchi-stocker',
    storageBucket: 'ouchi-stocker.appspot.com',
    iosBundleId: 'com.ukihome.ouchiStocker',
  );
}
